version: "2"
services:
  nginx:
    container_name: nginx-server
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - nodeapp
  nodeapp:
    container_name: nodeapp
    restart: always
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo-server      
  mongo-server:
    container_name: mongo-server
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - nginx-server
    command: certonly --webroot --webroot-path=/var/www/html --email ggilmay@eafit.edu.co --agree-tos --no-eff-email --staging -d bottled.ga  -d www.bottled.ga 



