version: "2"
services:
  nginx:
    container_name: nginx-server
    image: nginx
    volumes:
      - ./certbot/conf:/etc/nginx/ssl
      - ./certbot/data:/usr/share/nginx/html/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - nodeapp
  nodeapp:
    container_name: nodeapp
    restart: always
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo-server      
  mongo-server:
    container_name: mongo-server
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  certbot:
    image: certbot/certbot:latest
    command: cernanly --webroot --webroot-path=/usr/share/nginx/html/letsencrypt --email ggilmay@eafit.edu.co --agree-tos --no-eff-email -d bottled.ga
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/logs:/var/log/letsencrypt
      - ./certbot/data:/usr/share/nginx/html/letsencrypt

volumes:
  letsencrypt_certs: ~
  letsencrypt_www: ~

